### ISSUE TITLE
Something strange with event in calendar

### ISSUE THREAD

**Issue by creisle** [van-bug/van-bug.github.io#45]
I tried out the subscribe for our vanbug calendar and it shows our next vanbug at 2am on the 20th. can someone else try and let me know what they see?

![image](https://user-images.githubusercontent.com/4342641/211872583-6d60a993-c145-4571-bb82-b1dc25e1ea19.png)

**Comment by cmrn-rhi** [comment]
Very odd. I double checked the time zones of the events and they are for PT. I am currently subscribed to the calendar (on my gmail) and they all show up for me and at the correct times. I'll try subscribing with one of my backup gmails.

**Comment by cmrn-rhi** [comment]
It worked fine for me using the vanbug.org "Subscribe" link. Were you using the ics files?

![image](https://user-images.githubusercontent.com/48695054/211884715-a81d3289-46d9-491a-8eae-c3d8b43e95e5.png)

**Comment by creisle** [comment]
no i used the subscribe link too

**Comment by creisle** [comment]
It works correctly when i use my regular gmail (it added to my dev one before). I will see if there's anything funny going on with that account

**Comment by creisle** [comment]
Seems like that is it, for some reason that account is in GMT+00. Sorry for the confusion!

**Comment by cmrn-rhi** [comment]
S'all good! Always good to check/troubleshoot.
