### ISSUE TITLE
Lay-Terms Talks page not showing on home page

### ISSUE THREAD

**Issue by kmnip** [van-bug/van-bug.github.io#75]
As titled.
https://www.vanbug.org

I think it has to do with my PR #74.

**Comment by cmrn-rhi** [comment]
I think I've found and fixed the issue. Just installing poetry on my laptop to give it a test run before making a PR.

**Comment by cmrn-rhi** [comment]
Resolved with #76
Took me a little longer than it should've to get poetry happy enough to work for me :P
