### ISSUE TITLE
YouTube Upload - OCT 2023

### ISSUE THREAD

**Issue by cmrn-rhi** [van-bug/van-bug.github.io#95]
@sunsetyerin you expressed an interest in helping with the YouTube uploads, if you're up for it I would appreciate you attempting to put out our latest seminar on YouTube and provide feedback on whether our protocol/instructions are clear.

Instructions: https://github.com/van-bug/van-bug.github.io/issues/new
Recording: https://drive.google.com/file/d/1MoY3b9BIlta3I-jFCLJXRKQOV8BJVrlr/view?usp=sharing

Let us know either way. If you're down we'll help you get access to the account.

**Comment by sunsetyerin** [comment]
Yep! That sounds good to me @cmrn-rhi

**Comment by cmrn-rhi** [comment]
Taking this over to https://github.com/van-bug/development-group/issues/43
